.\" Manpage for tbx.
.\" Contact dev@gualdron.com to correct errors or typos.
.TH man 8 "02 April 2020" "1.0" "tbx man page"
.SH NAME
tbx \- Tabulate a delimited file at the command-line
.SH SYNOPSIS
tbx [OPTIONS] FILE [FILES]
.SH DESCRIPTION
tbx displays a delimited file in tabular form
.SH OPTIONS
tbx takes many options.
.SH EXAMPLES
The simplest way to use tbx is to simply call it with a file name.
.SH SEE ALSO
csv(3)
.SH BUGS
No known bugs.
.SH AUTHOR
Miguel Gualdron (dev@gualdron.com)

